version: '3.8'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - monkeyd

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - monkeyd

  mongodb:
    container_name: mongodb
    image: mongo:latest
    command: --bind_ip_all --replSet rs0
    ports:
      - '28017:27017'
    volumes:
      - mongodb_data_container:/data/db
      - ./scripts/mongodb/rs-init.sh:/scripts/rs-init.sh
    networks:
      mongo-network:
        aliases:
          - mongo.localhost
        ipv4_address: 172.20.0.2

volumes:
  mongodb_data_container:
  cache:
    driver: local

networks:
  monkeyd:
  mongo-network:
    name: mongo-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.254
